var str = "Hello User\nTHIS SITE IS NOT SECURE\nPLEASE LEAVE NOW\nWhy wont you leave\nVirus Detected\nLoading Virus...\nVirus Loaded\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDo Not Scroll Down\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\I SAID DONT SCROLL\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nNOOOOOOOOOOOOO!!!!!!!\n\n\n\n\nVIRUS INJECTED INTO OS\n\n\n\n\n\n\n\n\n\n\n\n\nSTEALING ALL DATA ON COMPUTER\n\n\nTARGET REACHED\nVIRUS.EXE LAUNCHED \n\n\n\nVIRUS.EXE BOOTUP SUCCESSFUL\nHAHAHAHAHAHA\n\n\n\nHAHAHAHAHAHAHA\n???????\nOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\nOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\nWHO LIVES IN A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE UNDER A PINEAPPLE UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n UNDER A PINEAPPLE\n  YOUR_OS_CRASHED";  
	document.getElementById("type").style.color = "red";
	var array = str.split("");
    var timer=5;
	

    function looper() {
      if (array.length > 0) {
        document.getElementById("type").innerHTML += array.shift();
      } else {
        clearTimeout(looper);
      }
      timer = setTimeout('looper()', 85);
    }
    looper();
